CREATE PROC NUEVA_FABRICACION_LISTAR
AS

SELECT N.IDNUEVAFABRICACION AS 'NRO DE FABRICACION', N.FECHA_INICIO AS 'FECHA DE INICIO',
N.OBSERVACIONES AS 'NOTAS', F.FABRICACION_NOMBRE,t.ORDEN_TAREA ,T.NOMBRE_TAREA, U.USUARIO_NOMBRE AS 'REALIZA',
U1.USUARIO_NOMBRE AS 'CONTROL 1', U2.USUARIO_NOMBRE AS 'CONTROL 2'

FROM NUEVA_FABRICACION N JOIN PROCESO_FABRICACION P ON N.IDNUEVAFABRICACION=P.NRO_FABRICACION
LEFT JOIN TAREA T ON P.TAREA_ID=T.FABRICACION_ID
JOIN FABRICACION F ON P.FABRICACION_ID=F.IDFABRICACION
JOIN USUARIO U ON P.REALIZA=U.IDUSUARIO
JOIN USUARIO U1 ON P.CONTROLUNO=U1.IDUSUARIO
JOIN USUARIO U2 ON P.CONTROLDOS=U2.IDUSUARIO
